version: '3.8'

services:

  sems:
    build:
      context: .
      dockerfile: Dockerfile.multi
      target: development
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/db_sems
      - MYSQL_USER=sems_app
      - MYSQL_PASS=sems_password
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver

  mysqlserver:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=db_sems
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=sems_app
      - MYSQL_PASSWORD=sems_password
    volumes:
      - sems_mysql_data:/var/lib/mysql
      - sems_mysql_config:/etc/mysql/conf.d

volumes:
  sems_mysql_data:
  sems_mysql_config: